In [6]:
import torch

In [7]:
print(torch.cuda.is_available())

True


In [8]:
x = torch.arange(0,13,2)


In [9]:
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12])


In [10]:
x.device

device(type='cpu')

In [11]:
x.numel()
x.shape

torch.Size([7])

In [12]:
x.size()

torch.Size([7])

In [13]:
x.numel()

7

In [14]:
y = torch.ones(6)

In [15]:
print(y)

tensor([1., 1., 1., 1., 1., 1.])


In [16]:
y.reshape([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [17]:
var = torch.randn([3,4])

In [18]:
var

tensor([[-0.1590,  1.5354,  0.7106,  0.7535],
        [ 0.3184, -0.3915,  1.4617, -0.6651],
        [-0.4450, -0.3923, -1.0304,  0.0744]])

In [19]:
var[0,:] 

tensor([-0.1590,  1.5354,  0.7106,  0.7535])

In [20]:
var[0:1,:]

tensor([[-0.1590,  1.5354,  0.7106,  0.7535]])

In [21]:
y = var[-1,:]
y

tensor([-0.4450, -0.3923, -1.0304,  0.0744])

In [22]:
lastrow = var[-1]
lastrow

tensor([-0.4450, -0.3923, -1.0304,  0.0744])

In [23]:
x = lastrow[lastrow > 0]
x

tensor([0.0744])

In [24]:
larger_than_0 = y.numpy()

In [25]:
result = []

for num in larger_than_0:
    if num > 0:
        print(num)
        result.append(num)


0.07436544


In [26]:
a = torch.FloatTensor(result)
a

tensor([0.0744])

In [27]:
var

tensor([[-0.1590,  1.5354,  0.7106,  0.7535],
        [ 0.3184, -0.3915,  1.4617, -0.6651],
        [-0.4450, -0.3923, -1.0304,  0.0744]])

In [28]:
var**2

tensor([[0.0253, 2.3575, 0.5050, 0.5677],
        [0.1014, 0.1533, 2.1367, 0.4424],
        [0.1980, 0.1539, 1.0617, 0.0055]])

In [29]:
b = torch.randn([3,1])
b


tensor([[-1.9413],
        [-0.4475],
        [ 0.0955]])

In [30]:
torch.pow(var,2)

tensor([[0.0253, 2.3575, 0.5050, 0.5677],
        [0.1014, 0.1533, 2.1367, 0.4424],
        [0.1980, 0.1539, 1.0617, 0.0055]])

In [31]:
c = torch.randn([3,4])
c

tensor([[ 1.3363,  2.1941,  0.5851,  0.7990],
        [ 0.2525,  0.4424,  1.0606,  0.5411],
        [ 0.8181,  0.0363, -0.1959,  0.1700]])

In [32]:
torch.add(c,b)

tensor([[-0.6050,  0.2528, -1.3563, -1.1423],
        [-0.1950, -0.0051,  0.6131,  0.0936],
        [ 0.9136,  0.1318, -0.1004,  0.2655]])

In [33]:
torch.pow(var, b)

tensor([[   nan, 0.4350, 1.9411, 1.7323],
        [1.6687,    nan, 0.8438,    nan],
        [   nan,    nan,    nan, 0.7803]])

In [34]:
var

tensor([[-0.1590,  1.5354,  0.7106,  0.7535],
        [ 0.3184, -0.3915,  1.4617, -0.6651],
        [-0.4450, -0.3923, -1.0304,  0.0744]])

In [35]:
b

tensor([[-1.9413],
        [-0.4475],
        [ 0.0955]])

In [36]:
var = var.reshape(12,)


In [37]:
b = b.reshape(3,)
c = torch.ones(9,)
d = torch.cat([b,c])


In [38]:
d

tensor([-1.9413, -0.4475,  0.0955,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000,  1.0000,  1.0000])

In [39]:
torch.dot(var,d)

tensor(-0.6269)

In [40]:
x = torch.randn(3,1,4)
y = torch.rand(1,3,4)
z = torch.rand(3,3,1)

x - y + z

tensor([[[-1.2550,  0.1540, -0.4670,  0.3781],
         [-0.6772,  1.1230,  0.5877,  0.8410],
         [-1.1941,  0.5339, -0.8266,  0.3196]],

        [[-0.5719, -1.2438, -2.4774,  0.6766],
         [-1.2296, -1.5103, -2.6582, -0.0960],
         [-1.0223, -1.3752, -3.3483,  0.1068]],

        [[-1.3551,  1.2235, -0.8620, -2.7386],
         [-0.9293,  2.0405,  0.0406, -2.4278],
         [-1.0726,  1.8250, -1.0001, -2.5756]]])