In [63]:
import torch

In [64]:
print(torch.cuda.is_available())

True


In [65]:
x = torch.arange(0,13,2)


In [66]:
print(x)

tensor([ 0,  2,  4,  6,  8, 10, 12])


In [67]:
x.device

device(type='cpu')

In [68]:
x.numel()
x.shape

torch.Size([7])

In [69]:
x.size()

torch.Size([7])

In [70]:
x.numel()

7

In [71]:
y = torch.ones(6)

In [72]:
print(y)

tensor([1., 1., 1., 1., 1., 1.])


In [73]:
y.reshape([2,3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [74]:
var = torch.randn([3,4])

In [75]:
var

tensor([[-0.0176, -0.9377, -0.6876, -1.6531],
        [ 0.0312, -0.4713, -0.1432, -0.1009],
        [ 0.5842, -0.9174,  0.8183,  1.3662]])

In [76]:
var[0,:] 

tensor([-0.0176, -0.9377, -0.6876, -1.6531])

In [77]:
var[0:1,:]

tensor([[-0.0176, -0.9377, -0.6876, -1.6531]])

In [78]:
y = var[-1,:]
y

tensor([ 0.5842, -0.9174,  0.8183,  1.3662])

In [79]:
lastrow = var[-1]
lastrow

tensor([ 0.5842, -0.9174,  0.8183,  1.3662])

In [80]:
x = lastrow[lastrow > 0]
x

tensor([0.5842, 0.8183, 1.3662])

In [81]:
larger_than_0 = y.numpy()

In [82]:
result = []

for num in larger_than_0:
    if num > 0:
        print(num)
        result.append(num)


0.5842384
0.81834257
1.3661983


In [83]:
a = torch.FloatTensor(result)
a

tensor([0.5842, 0.8183, 1.3662])

In [84]:
var

tensor([[-0.0176, -0.9377, -0.6876, -1.6531],
        [ 0.0312, -0.4713, -0.1432, -0.1009],
        [ 0.5842, -0.9174,  0.8183,  1.3662]])

In [85]:
var**2

tensor([[3.1111e-04, 8.7937e-01, 4.7273e-01, 2.7328e+00],
        [9.7505e-04, 2.2212e-01, 2.0512e-02, 1.0190e-02],
        [3.4133e-01, 8.4164e-01, 6.6968e-01, 1.8665e+00]])

In [86]:
b = torch.randn([3,1])
b


tensor([[-1.3387],
        [ 0.7992],
        [-0.6956]])

In [87]:
torch.pow(var,2)

tensor([[3.1111e-04, 8.7937e-01, 4.7273e-01, 2.7328e+00],
        [9.7505e-04, 2.2212e-01, 2.0512e-02, 1.0190e-02],
        [3.4133e-01, 8.4164e-01, 6.6968e-01, 1.8665e+00]])

In [88]:
c = torch.randn([3,4])
c

tensor([[-0.3853, -0.2574, -0.4681,  0.8620],
        [-0.8696,  0.8352,  2.0697,  0.2056],
        [ 1.0253, -0.5314,  1.5265, -1.0209]])

In [62]:
torch.add(c,b)

tensor([[-1.0468, -1.5000, -0.7368,  1.4151],
        [-1.7926,  0.9916, -2.2973,  1.2119],
        [ 0.7766,  1.1024,  1.1646,  1.0717]])

In [89]:
torch.pow(var, b)

tensor([[   nan,    nan,    nan,    nan],
        [0.0626,    nan,    nan,    nan],
        [1.4533,    nan, 1.1496, 0.8049]])

In [90]:
var

tensor([[-0.0176, -0.9377, -0.6876, -1.6531],
        [ 0.0312, -0.4713, -0.1432, -0.1009],
        [ 0.5842, -0.9174,  0.8183,  1.3662]])

In [91]:
b

tensor([[-1.3387],
        [ 0.7992],
        [-0.6956]])

In [105]:
var = var.reshape(12,)


In [112]:
b = b.reshape(3,)
c = torch.ones(9,)
d = torch.cat([b,c])


In [113]:
d

tensor([-1.3387,  0.7992, -0.6956,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
         1.0000,  1.0000,  1.0000,  1.0000])

In [114]:
torch.dot(var,d)

tensor(-0.7335)

In [121]:
x = torch.randn(3,1,4)
y = torch.rand(1,3,4)
z = torch.rand(3,3,1)

x - y + z

tensor([[[-1.1469,  1.7781, -0.0443, -0.4234],
         [-2.4599,  0.8936, -0.4037, -0.3973],
         [-1.2857,  1.5191, -0.3335, -0.2250]],

        [[ 0.1402, -0.5579, -0.7568, -1.3068],
         [-0.5445, -0.8141, -0.4878, -0.6523],
         [ 0.8108, -0.0074, -0.2365, -0.2989]],

        [[-0.4420,  0.4905,  0.1976,  0.5302],
         [-0.9236,  0.4373,  0.6696,  1.3877],
         [ 0.1525,  0.9649,  0.6418,  1.4620]]])